### ISSUE TITLE
Matplotlib bug

### ISSUE THREAD

**Issue by Shesui** [krakodjaba/TelAnalysis#2]
C:\Program Files\Python310\lib\site-packages\networkx\drawing\nx_pylab.py:108: UserWarning: Starting a Matplotlib GUI outside of the main thread will likely fail.
  cf = plt.gcf()

**Comment by krakodjaba** [comment]
yes, we already know about this error, but I do not know how to get rid of it, since it is not critical, as long as it remains so.

**Comment by Shesui** [comment]
Not critical
